#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# keyring
# eval $(/usr/bin/gnome-keyring-daemon --start)
# export SSH_AUTH_SOCK

# autostart apps
# exec /usr/lib/notification-daemon-1.0/notification-daemon &
exec /home/adhiwena/.screenlayout/monitor.sh &
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec xsetroot -cursor_name left_ptr &
exec numlockx & picom & urxvtd &
exec feh --bg-fill /home/data/Github/wallpapers/landscapes/tropic_island_day.jpg &
# exec feh --recursive --bg-fill --randomize /home/data/Github/wallpapers/* &
# exec feh --bg-fill --randomize /home/adhiwena/Pictures/Wallpaper/dark/* &
exec bspwm # polybar inside bspwm

