#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Screenkey manage=off

# floating
bspc rule -a '*' state=floating center=on

floatingApps=(\
  Lxappearance \
  Timeshift-gtk \
  Font-manager \
  kitty:bpytop \
  kitty:nnn \
  Pavucontrol
)

for app in ${floatingApps[@]}; do
  bspc rule -a $app sticky=on rectangle=1500x800+0+0
done

# tiled
bspc rule -a kitty:terminal desktop='^1' state=tiled follow=on
bspc rule -a firefox desktop='^2' state=tiled follow=on
bspc rule -a Code:code desktop='^3' state=tiled follow=on
bspc rule -a mpv desktop='^4' state=tiled follow=on # mpv also in desktop 4

# autostart polybar
exec ~/.config/polybar/launch.sh &
